### PR TITLE
Build mixxx 2.3 instead of using the debian repos

### PR DESCRIPTION
**Pull request by fayaaz**

### CODE REVIEW

**Comment by BlueForrest** [comment]
Hi, i'm not so familiar with installing software on a raspberry PI.
I have an RPI4-4GB version and want to install your build mixx 2.3.
I processed as follows:
- Downloaded the files
- burned image to SD card
- copied mixxx-pi-gen-0.3.0.zip into the root of the SD card.
- put the SD card into my RPI and powerd it on.

Now it seems to do something, I see a few times the rainbow screen coming up, but after a few seconds I get a black screen and nothing happens anymore.
How long it takes to load or installing this? 
Can you provide me some better NOOBS instructions, how to install this? I have the feeling i'm doing something stupid or not in the correct order.


Regards,
Johan

**Comment by dennisdebel** [comment]
Hi Johan,

How did you copy the .zip to the sd card?

Best,
Dennis

**Comment by BlueForrest** [comment]
Hi Denis, I did this under win10 explorer, moved the zip file on the SD card after I had created the image file.
Image was created with a program  "USB Image Tool".

Johan

**Comment by fayaaz** [comment]
Hi Johan,

It does indeed take a bit of time on the first startup - you should see it resizing the FS and rebooting first thing. The first boot to mixxx takes a while so it may be worth waiting. The other option is to plug it into an ethernet slot and try and reach it via SSH to see what it is doing and if indeed it has got to full boot. 
I had problems with HDMI1 and HDMI2 as well and switching between them seemed to solve black screens.

Your step here is worrying though:
> copied mixxx-pi-gen-0.3.0.zip into the root of the SD card.

As @dennisdebel  has said have you accidentally imaged the zip file instead of the .img file within?

I have also set up 'Issues' on this repo. Feel free to open an issue if you still have problems.

**Comment by dennisdebel** [comment]
If i understand correctly: From what I read it seems this USB Image Tool
makes an image from a mass data storage device but you need to put an image
to an mass storage device. Try for example BalenaEtcher (balena.io) to
flash the .zip to your sdcard.

**Comment by BlueForrest** [comment]
Thanks for the reply's, I will use BalenaEtcher for the image and retry it - while checking via SSH what is happening.

**Comment by fayaaz** [comment]
I have added a step-by-step to the readme to help people flash the image using BalenaEtcher :)

**Comment by BlueForrest** [comment]
Thanks for doing that.👌

Op zo 22 nov. 2020 om 00:40 schreef Fayaaz Ahmed <notifications@github.com>:

**Pull request merged**
